//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PiwikPRO_InstallScriptUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ToolTipTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ToolTipTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PiwikPRO_InstallScriptUI.ToolTipTexts", typeof(ToolTipTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part of your API credentials. You can create it in Menu &gt; Profile &gt; API credentials..
        /// </summary>
        internal static string PiwikPROClientID {
            get {
                return ResourceManager.GetString("PiwikPROClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Piwik PRO account address with containers added to the address.
        ///
        ///For standard domains: https://yourname.containers.piwik.pro
        ///For custom domains: https://yourname.piwik.pro/containers
        ///
        ///This address may be different for Piwik PRO on-premises or private cloud accounts. Contact us to get the right address..
        /// </summary>
        internal static string PiwikPROContainer {
            get {
                return ResourceManager.GetString("PiwikPROContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part of your API credentials. You can create it in Menu &gt; Profile &gt; API credentials..
        /// </summary>
        internal static string PiwikPROSecret {
            get {
                return ResourceManager.GetString("PiwikPROSecret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address you use to log in to Piwik PRO. Example: https://yourname.piwik.pro.
        /// </summary>
        internal static string PiwikPROServiceUrl {
            get {
                return ResourceManager.GetString("PiwikPROServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example: https://contoso.sharepoint.com.
        /// </summary>
        internal static string SharepointURL_Online {
            get {
                return ResourceManager.GetString("SharepointURL_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL to your Sharepoint WebApplication
        ///Example: https://yoursharepointwebapp.com.
        /// </summary>
        internal static string SharepointURL_OnPrem {
            get {
                return ResourceManager.GetString("SharepointURL_OnPrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want to activate feature tracking of all newly created site collections,
        ///it activates only feature of tracker (which add custom action to settings menu
        ///which name “Piwik PRO&quot;) but not the tracking. Activation of tracking is inside &quot;Piwik PRO&quot; settings form..
        /// </summary>
        internal static string SPActivateStapplerFeature {
            get {
                return ResourceManager.GetString("SPActivateStapplerFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A global admin account on your SharePoint tenant. 
        ///Example: admin@contoso.onmicrosoft.com.
        /// </summary>
        internal static string SPAdminLogin_Online {
            get {
                return ResourceManager.GetString("SPAdminLogin_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A farm admin account. 
        ///Example: domain\username.
        /// </summary>
        internal static string SPAdminLogin_OnPrem {
            get {
                return ResourceManager.GetString("SPAdminLogin_OnPrem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, the resource group is created in the West Europe region or inherits the existing location.
        ///You can use a custom location. Example: westeurope, uswest..
        /// </summary>
        internal static string SPOnline_AzureLocation {
            get {
                return ResourceManager.GetString("SPOnline_AzureLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of a new or existing resource group..
        /// </summary>
        internal static string SPOnline_AzureResourceGroup {
            get {
                return ResourceManager.GetString("SPOnline_AzureResourceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure subscription name or resource group ID..
        /// </summary>
        internal static string SPOnline_AzureSubscription {
            get {
                return ResourceManager.GetString("SPOnline_AzureSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure tenant name or resource group ID..
        /// </summary>
        internal static string SPOnline_AzureTenant {
            get {
                return ResourceManager.GetString("SPOnline_AzureTenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A suffix added to the web app name. Example: piwikpro&lt;webAppSuffix&gt;.
        ///The suffix needs to be globally unique in Microsoft Azure. You can use your company’s name. You can use letters and numbers..
        /// </summary>
        internal static string SPOnline_AzureWebAppSuffix {
            get {
                return ResourceManager.GetString("SPOnline_AzureWebAppSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For a standard installation, keep this option enabled. We&apos;ll install the WebJob on your Azure tenant. The WebJob connects Piwik PRO to SharePoint and registers new site collections that can be tracked.
        ///
        ///If this option is disabled, you&apos;ll need to register new site collections manually in Piwik PRO..
        /// </summary>
        internal static string SPOnline_IncludeAzure {
            get {
                return ResourceManager.GetString("SPOnline_IncludeAzure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s a unique ID for each site or app in Piwik PRO. You can find it in Menu &gt; Administration &gt; Sites &amp; apps &gt; Pick a site or app. The ID is under the site or app name..
        /// </summary>
        internal static string SPOnline_PiwikPROSiteID {
            get {
                return ResourceManager.GetString("SPOnline_PiwikPROSiteID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked, the SPFx package will be installed in the site collection app catalog
        ///(not in the tenant app catalog) and available only for the site collection specified in SharePointUrl.
        ///To install more site collections, rerun this script with a different SharePointUrl..
        /// </summary>
        internal static string SPOnline_UseSiteScope {
            get {
                return ResourceManager.GetString("SPOnline_UseSiteScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep it checked if you use multi-factor authentication for your SharePoint account..
        /// </summary>
        internal static string SPOnline_UseWebLogin {
            get {
                return ResourceManager.GetString("SPOnline_UseWebLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional - secondary admin account, will be added to sitecollection administrators in newly created PiwikAdmin site.
        ///This admin will be able to access the form of configuration Piwik PRO Sharepoint connector.
        ///f.e. admin2@contoso.onmicrosoft.com.
        /// </summary>
        internal static string SPSecondAdminLogin_Online {
            get {
                return ResourceManager.GetString("SPSecondAdminLogin_Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional - secondary admin account, will be added to sitecollection administrators in newly created PiwikAdmin site.
        ///This admin will be able to access the form of configuration Piwik PRO Sharepoint connector.
        ///in format: domain\username.
        /// </summary>
        internal static string SPSecondAdminLogin_OnPrem {
            get {
                return ResourceManager.GetString("SPSecondAdminLogin_OnPrem", resourceCulture);
            }
        }
    }
}
